### ISSUE TITLE
Question on Watermark and Text

### ISSUE THREAD

**Issue by bchiu-barfoot** [imazen/imageflow-dotnet-server#10]
Hi, 

We are investigating on migrating from ImageResizer to Imageflow (dotnet server). 
One of our use cases is applying dynamic text (run time query string) for watermarking, which was supported in ImageResizer. 

However I couldn't see any documentations on how this would work with Imageflow-dotnet-server. 
Could you please confirm whether it's supported at the moment? If so, could you provide an example?

Thanks

**Comment by lilith** [comment]
Text watermarking is not supported and probably won't be in the near
future. It has a lot of security and performance downsides.

**Comment by bchiu-barfoot** [comment]
Thanks a lot on the quick response!
