### ISSUE TITLE
Logging Issue

### ISSUE THREAD

**Issue by gerneio** [imazen/imageflow-dotnet-server#17]
Small issue, one I wasn't aware of until just now, but the ILogger format strings are not being used properly.

According to [this](https://stackoverflow.com/questions/56278618/why-ilogger-is-not-able-to-use-the-same-position-of-the-arguments-array-multiple) SO post: 

> Microsoft.Extensions.Logging uses structured logging. This means that the placeholders are not numbers which refer to the different args passed, but are instead names which are associated with each of the args.

Here are the official docs on this LogTrace method: [LINK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loggerextensions.logtrace?view=dotnet-plat-ext-3.1#Microsoft_Extensions_Logging_LoggerExtensions_LogTrace_Microsoft_Extensions_Logging_ILogger_Microsoft_Extensions_Logging_EventId_System_String_System_Object___)

One of the places I noticed this at was within the CleanupWorker.DoTask method, but Looks like you are using the position reference format across all instances where you are logging info. Looks like if you at least keep the order of parameters sequential as compared to how you use them in the string, then it'll work just fine.

**Comment by gerneio** [comment]
Example of invalid Log statement:

`logger?.LogTrace("{2}ms: Executing task {0} {1} ({3} tasks remaining)", item.Task.ToString(), item.RelativePath, sw.ElapsedMilliseconds.ToString(NumberFormatInfo.InvariantInfo).PadLeft(4), queue.Count.ToString(NumberFormatInfo.InvariantInfo));`

**Comment by lilith** [comment]
Thanks for reporting this!
