### ISSUE TITLE
Disk Caching

### ISSUE THREAD

**Issue by gerneio** [imazen/imageflow-dotnet-server#18]
I've been digging into a lot of the disk caching source code so that I can better understand how it operates and how to mold it to our needs. I understand it mostly, but not entirely:

1) I noticed that on application start that ClassicDiskCache.StartAsync() is what calls CleanupManager.CleanAll(), which in turn adds the entirety of the cache directory recursively to the queue list for cleanup processing. However, once the queue processes the list, and each item is removed from the queue, the items that were NOT ready to be removed don't seem to be re-queued at any point in the future for further processing. It seems this whole directory cleanup process only works on application start. Am I missing something? Is there a way to have the CleanAll process queue up say every hour or something?
2) When file removal DOES finally occur, IF the sub-folder is empty, it is NOT removed also. Is there suppose to be a process in place for this?
3) I am still having a hard time understanding how the sub-folder name is generated, however, I did just stumble across the UrlHasher class where it seems this logic is kept. So I'll investigate this in more detail next week, but would appreciate whatever info you could provide on how the folder name logic works. Originally what I thought would be the case is that each folder would be a hash representation of the relative path of the image URL, and then the image filename would be a hash of some sort on the entire URL with query params and all, but seems that is not the case. So in what cases would the same folder name be used for more than ONE image? Or is this just only something you would see happen when you are processing thousands and thousands of images, rather than just a few test images?

**Comment by lilith** [comment]
You'll only see multiple images in a folder once you have thousands (or more than the default subfolder count) of images.

**Comment by lilith** [comment]
1. There's no need to CleanAll every hour - whenever a file is added to a subfolder that subfolder is cleaned. https://github.com/imazen/imageflow-dotnet-server/blob/08c1a6542b90d5ef0297112b53e6dbf55c2e05e7/src/Imazen.DiskCache/Cleanup/CleanupManager.cs#L60
2. Empty subfolders are preserved, not removed. Generally cleanup will never remove *all* files from a folder, just limit it to 400. 
3. The subfolder name is just the end part of the hash. It's designed to distribute files evenly among directories.

**Comment by gerneio** [comment]
1. But that is only going to queue the sub-folder for cleaning, right? Not the entire directory. I need the entire directly to be marked for cleaning at GUARANTEED intervals. The reason being is that currently, we have no guarantees (just chance), that another file will be added to a directory with "old" image files. So on application start, the process for CleanAll is queued, but only the once. So if there are files that won't be flagged for the "removal" process yet, but will eventually fall within the removal date range DURING the execution of the program, they won't be re-queued for removal until AFTER either another file is added to the same sub-folder (not guaranteed), or the app pool is recycled (or some other restart mechanism). I basically want to have all files removed that haven't been accessed within a certain period of time, regardless of # of files per subdirectory. If something can't be done about this from within the program itself, **can I at least queue my own tasks within CleanupManager's CleanupQueue?** Could be that I am just underestimating how often these sub-directories are going to be written to, however in our use case, for every ONE image stored on our server, there will be an average of two types of images (one watermarked and one thumb) generated in the cache for them, as we control ALL the settings server-side, and won't be accepting any incoming parameters from the URL. The goal is to have the smallest footprint possible for this disk caching folder, but of course with minimal performance impacts.
2. I suppose I'm not too worried about empty subdirectories.
3. Understood.
4. I may have an additional problem but I will need to investigate further to give you some more tangible information to go on. Basically, when CleanupManager.UsedFile queues a FlushAccessedDate work item, sometimes when that event is finally executed within CleanupManager.FlushAccessedDate(), the File.SetLastAccessTimeUtc() method will throw an error of: "The process cannot access the file 'XXX' because it is being used by another process." Typically this error happens immediately when the image file is accessed from its web endpoint, but other times the work item is queued and executed at a later point. I think this is more of an issue of when the work item is executed immediately that the current web request still has a handle on the cached file, so maybe what needs to happen in the CleanupManager.FlushAccessedDate() method is some try/catch logic that when it fails, it just re-queues the work item to be run at a later point. Just a thought.

**Comment by gerneio** [comment]
FYI, on item 4, here is some of the debug output of when that error occurs:

```
Imageflow.Server.ImageflowMiddleware: Information: Serving /LTGTEST/0D212704/0D212704-02d.jpg?width=1&scale=both&watermark=LTGTEST.LTG_Group.LTG from disk cache 072b/ca2b0b016e5a71955e6433b481cb09282a3a2d045d8374d0ba6d65a527b13d2b.jpg
Imageflow.Server.DiskCache.DiskCacheService: Information:    1ms: Executing task FlushAccessedDate 072b/ca2b0b016e5a71955e6433b481cb09282a3a2d045d8374d0ba6d65a527b13d2b.jpg (0 tasks remaining)
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.

System.IO.IOException: The process cannot access the file '..\image_cache\072b\ca2b0b016e5a71955e6433b481cb09282a3a2d045d8374d0ba6d65a527b13d2b.jpg' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.OpenRead(String path)
   at Imageflow.Server.ImageflowMiddleware.ServeFileFromDisk(HttpContext context, String path, String etag, String contentType) in ..\repos\imageflow\imageflow-dotnet-server\src\Imageflow.Server\ImageflowMiddleware.cs:line 227
   at Imageflow.Server.ImageflowMiddleware.ProcessWithDiskCache(HttpContext context, String cacheKey, ImageJobInfo info) in ..\repos\imageflow\imageflow-dotnet-server\src\Imageflow.Server\ImageflowMiddleware.cs:line 220
   at Imageflow.Server.ImageflowMiddleware.Invoke(HttpContext context) in ..\repos\imageflow\imageflow-dotnet-server\src\Imageflow.Server\ImageflowMiddleware.cs:line 132
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by gerneio** [comment]
And in case you need to know, these are what I have my CleanupStrategry settings set to (for testing purposes of course):

```
CleanupStrategy = new Imazen.DiskCache.CleanupStrategy() { 
    StartupDelay = TimeSpan.FromSeconds(10),
    MinDelay = TimeSpan.FromSeconds(30),
    MaxDelay = TimeSpan.FromSeconds(60),
    //MaximumItemsPerFolder = 1,
    TargetItemsPerFolder = 0,
    AvoidRemovalIfCreatedWithin = TimeSpan.FromMinutes(20),
    AvoidRemovalIfUsedWithin = TimeSpan.FromMinutes(20),
    ProhibitRemovalIfCreatedWithin = TimeSpan.FromMinutes(15),
    ProhibitRemovalIfUsedWithin = TimeSpan.FromMinutes(15)
} 
```

**Comment by lilith** [comment]
Regarding 1 - that's really not how DiskCache is designed to work. You may need your own disk cache implementation if that's what you want. 
Regarding 4 - DiskCache passes off filenames to Imageflow.NET Server, so it can't know when the file is going to be locked after it is written. We intentionally let FlushAccessedDate fail because it really doesn't matter very much.

**Comment by gerneio** [comment]
1. Understood, I'll try to see what I can do on my own. If I could at least have an entry point to queue my own items, that would be sufficient enough for me to implement my use case.
4. The error I shared with you is propagating to the top level, so the image request itself is erroring out, so I would say it matters quite a bit:

![image](https://user-images.githubusercontent.com/13949170/90439422-2abfff80-e09b-11ea-9044-76dfb9a18830.png)

**Comment by gerneio** [comment]
Further investigation on item 4 seems to lead to a "race" condition. The issue only seems to occur when:

1) The image being requested is already cached
2) The `CleanupQueue` is currently empty
3) And time since last work or busy has exceeded `CleanupStrategy` settings (see above for my settings; kept short for testing; needed to wait about 1 min after making 1st initial call)

The issue seems to ONLY affect the FIRST image that runs into this scenario. For example, making a request for 500 images back to back, the error is only produced on the first image.

The root of the error occurs during the `ImageflowMiddleware.ProcessWithDiskCache()` method. The `ClassicDiskCache.GetOrCreate(`) method will add a `FlushAccessDate` work item to the queue IF the image is cached. If the request at hand matches the 3 conditions above, then the "race" condition can occur. Since the `CleanupWorker.MayHaveWork()` method triggers the `CleanupWorker`'s main thread/process to continue execution and work on the queue, the `ProcessWithDiskCache()` method continues on at the same time, eventually getting down to the `ServeFileFromDisk()` method which makes a call to `File.OpenRead()`. Since both of these methods are executing in tangent, you will constantly run into the error: "_The process cannot access the file 'XXX' because it is being used by another process._" Sometimes the error propagates up to the request level IF the `ServeFileFromDisk()` is the method that loses the race, and sometimes the `CleanupWorker `will lose the race and throw the error.

The only solution I've gotten to work thus far is to add a short `Thread.Sleep(1000)` delay just before the `DoWorkFor()` method call in the `CleanupWorker.mainInner()` while loop. So far seems to be preventing either error from propagating

**Comment by gerneio** [comment]
@lilith Wondering if you've had time to contemplate my last reply? I've been testing with the "Thread.Sleep" change and haven't run into any more of these access errors.

**Comment by gerneio** [comment]
@lilith We're not too far away from going live with our code using your library, however, was hoping to get a working fix pushed to the code base for the issue I outlined in my previous reply before we do. As it stands we wouldn't be able to use the cleanup process without this issue being addressed.

**Comment by lilith** [comment]
I'll need to thoroughly review the fix. It might be better to not queue the
flushaccesseddate when creating a new file in the first place.

**Comment by lilith** [comment]
So, I've found a solution that I'd like you to test. It causes the FlushAccessDate task to not even be queued until 10 or more seconds after the request is made. This is in v0.3.8

https://github.com/imazen/imageflow-dotnet-server/releases/tag/v0.3.8

The code changes can be seen here: https://github.com/imazen/imageflow-dotnet-server/commit/35e71ff811a0ab34ae240f174f238fcdadfb21cd

Please re-open if the issue persists, or open an new issue if you have any remaining questions about DiskCache.
