### ISSUE TITLE
IIS Virtual Directory Issue ASP.NET Core 3.1

### ISSUE THREAD

**Issue by MichaelSamteladze** [imazen/imageflow-dotnet-server#19]
Images are not resizing when directory is registered as IIS virtual directory.

**Comment by lilith** [comment]
ASP.NET Core ignores IIS virtual directories. Use MapPath in Startup.cs instead.

**Comment by MichaelSamteladze** [comment]
I have upload directory for my website which is outside root directory of website. Upload directory servers images and all other type of files.  All works fines, files can be downloaded, images can be viewed. 
When it comes to imageflow, I can still view images, the only problem is that resize function is not working.

Any solution for that?

**Comment by gerneio** [comment]
@MichaelSamteladze May want to share some code to give us a better idea of your setup. You can see an example of this in the example Startup.cs. Note that this can be an external directory outside site root (or network path, if you're clever), such is my use case.

https://github.com/imazen/imageflow-dotnet-server/blob/08c1a6542b90d5ef0297112b53e6dbf55c2e05e7/examples/Imageflow.Server.Example/Startup.cs#L92

**Comment by lilith** [comment]
For more info see https://stackoverflow.com/questions/62894772/net-core-resizing-images-using-imageflow/63082653?noredirect=1#comment112286494_63082653
