### ISSUE TITLE
Imageflow.Net.Server is pinned to ASP.NET Core 2.2

### ISSUE THREAD

**Issue by danielcrenna** [imazen/imageflow-dotnet-server#2]
It looks like in order to stay on `netstandard2.0`, the `Imageflow.Net.Server` middleware is referencing the legacy AspNetCore packages. 

Unfortunately you can only get past this by switching to `netcoreapp3.1` (or `netcoreapp5.0`) and using `FrameworkReference`.

I was going to issue a PR but want to know the rationale for using `netstandard2.0` before I potentially waste time.

**Comment by lilith** [comment]
We don't need to stay on .NET standard since this is a .NET Core-only project. The Imageflow.Net bindings are .net standard and the helpers should be but the middleware can be changed.

**Comment by lilith** [comment]
A PR would be great. BTW thank you so much for your support over the years! It matters.
