### ISSUE TITLE
Hard Coded Azure Containers

### ISSUE THREAD

**Issue by hn1** [imazen/imageflow-dotnet-server#23]
When using ImageFlow Server, it seems one has to hard code the Azure Containers in Startup of an MVC Core application.
As we are creating containers dynamically, is there any way one can avoid this?

It is suggested that we use our own blob provider. Any idea how this can be done?
We would prefer to use proven solutions as opposed to roll out our own. Even better would be if this functionality was available in Imageflow.
Thanks

**Comment by lilith** [comment]
I would suggest looking at the AzureBlobService to see how it works.

https://github.com/imazen/imageflow-dotnet-server/blob/main/src/Imageflow.Server.Storage.AzureBlob/AzureBlobService.cs

You'll need to implement 3 methods: GetPrefixes(), SupportsPath(string) and
Fetch(string)

**Comment by hn1** [comment]
Thanks for your guidance.
It seems the List<PrefixMapping> mappings property needs to also be pre-determined. 
If that s the case, this won't work in situation where an application is creating containers on the fly.
And if this is not the case, where would one plug this class in.
Sorry, we are not very familiar with these things.
Another option is that if you will include this feature, we wait for that.
Many thanks.

**Comment by lilith** [comment]
I've added an example class that does what you need. https://github.com/imazen/imageflow-dotnet-server/blob/379320000fb8283fa65efc372ab99627a770958f/examples/Imageflow.Server.Example/CustomBlobService.cs

You can see how it is configured by looking at Startup.cs in the Imageflow.Server.Example project.

**Comment by hn1** [comment]
Thank you so much for this first class support.
