### ISSUE TITLE
AWS ServiceURL support

### ISSUE THREAD

**Issue by danbeneventano** [imazen/imageflow-dotnet-server#24]
In the constructor for `AmazonS3Client`, `AmazonS3Config` has the option `ServiceURL` which allows use of a custom AWS endpoint. This is needed if you are trying to use alternate implementations of AWS, such as DigitalOcean Spaces.

In `MapPrefix`, it would be nice to pass a `ServiceURL` as the second parameter, instead of a `RegionEndpoint`.

**Comment by lilith** [comment]
I've added an overload that lets you provide your own AmazonS3Config instance. I just released this as v0.3.9 -> https://github.com/imazen/imageflow-dotnet-server/releases/tag/v0.3.9

**Comment by danbeneventano** [comment]
Awesome, thanks for releasing it so quick!
