### ISSUE TITLE
Dots in sanitize

### ISSUE THREAD

**Issue by drphrozen** [imazen/imageflow-dotnet-server#28]
Shouldn't these be without the dot?

https://github.com/imazen/imageflow-dotnet-server/blob/f7f0b4abd1bb855ef97e096aa0ae5be82e121b85/src/Imageflow.Server/PathHelpers.cs#L61-L64

**Comment by lilith** [comment]
The default fallback is "jpg", so this doesn't actually matter, but it looks wrong. Thanks for reviewing the source code!
