### ISSUE TITLE
Watermark handler doesn't apply watermark until width or maxwidth explicitly passed

### ISSUE THREAD

**Issue by AndreySierra** [imazen/imageflow-dotnet-server#29]
Hello,

Watermarks not working until query string contains w/width/maxwidth. Probably passing height could work too.
However watermarks working even passed empty or incorrect parameter (?w=).
Using .AddCommandDefault("w", "4096") for example doesn't help too. I had to pass empty width parameter.

Additionally AddWatermarkingHandler doesn't prevent default processing ?watermark query string parameter. As you can see in code below I passing watermark text and generating image with text on the fly, however I can't use w or watermark parameter name because both of them is reserved words. It would be good to allow watermarking handler intercept parameters first.
Or would be good to have query parameters preprocessor allowing to modify them or setup overriding values instead.

```
var options = new ImageflowMiddlewareOptions()
// Maps / to WebRootPath
.SetMapWebRoot(true)
// Allow Disk Caching
.SetAllowDiskCaching(true)
// Allow Sqlite Caching
.SetAllowSqliteCaching(false)
// We can only have one type of caching enabled at a time
.SetAllowDistributedCaching(false)
// Disable memory caching even if the service is installed
.SetAllowMemoryCaching(false)
// Cache publicly (including on shared proxies and CDNs) for 30 days
.SetDefaultCacheControlString("public, max-age=86400")
.AddCommandDefault("down.filter", "mitchell")
.AddCommandDefault("f.sharpen", "15")
.AddCommandDefault("webp.quality", "90")
.AddCommandDefault("ignore_icc_errors", "true")
//When set to true, this only allows ?preset=value URLs, returning 403 if you try to use any other commands. 
.SetUsePresetsExclusively(false)
.AddWatermarkingHandler("/", args => {
  if (args.Query.TryGetValue("wmk", out var text) && !string.IsNullOrEmpty(text)) {
	string md5 = text.CreateMd5();
	var imageGenerator = app.ApplicationServices.GetRequiredService<IImageTextGeneratorService>();
	var watermarkOptions = app.ApplicationServices.GetRequiredService<WatermarkOptions>();
	var fileName = imageGenerator.GetImageTextPath(text);
	args.AppliedWatermarks.Add(new NamedWatermark(md5, fileName, watermarkOptions));
  }
});
```

Thanks.

**Comment by lilith** [comment]
You can actually fix this with AddRewriteHandler(), which allows you to rewrite the 'watermark' query key to one that isn't reserved. 

Regarding needing "?w=" for AddWatermarkingHandler watermarks to be applied, that is an oversight I just fixed

**Comment by lilith** [comment]
Try v0.4.2

**Comment by AndreySierra** [comment]
Thanks a lot!
