### ISSUE TITLE
When should Imageflow.Server require .NET 5.0?

### ISSUE THREAD

**Issue by lilith** [imazen/imageflow-dotnet-server#34]
Upgrading should be easy, I'm just wondering what end-users would prefer. I don't plan on maintaining two versions.

**Comment by nza-dk** [comment]
I was actually just looking for a .Net 5.0 version of Imageflow for my own little project 🙂 
I can't imagine too many has moved to .Net 5.0 yet, so can't say when it should be a requirement. I think it depends on your feature roadmap. If you have no new features planned, then it would make sense to make the next version for .Net 5.0.
Then users on pre-5.0 could use a previous version without loosing any functionality?

**Comment by lilith** [comment]
I have a few features planned per the other issues, so I guess I'll wait.

Thanks for the feedback!

**Comment by Amethi** [comment]
I think this is premature. Historically, at least in my experience, upgrading framework versions has been simple in theory and complex in practice when faced with any app of maturity. 

It might be better to give people notice of intent to stop supporting pre-v5 and wait a year or so before making the jump.

**Comment by lilith** [comment]
Perhaps I should try to support both via multi-targeting. Are there examples of how that would work re: nuget packaging and the release process?

**Comment by nza-dk** [comment]
If it's possible, then definitely.
I see .NET 5 spreading faster than any previous versions 🙂

**Comment by lilith** [comment]
It should be possible, I just don't know how terribly messy it will get. And I can't seem to find an example of someone doing this already.

**Comment by lilith** [comment]
So... it looks like this is a non-issue. I can reference Imageflow.Server from a .NET 5 project as-is, and everything works. Please give it a try and let me know if I overlooked something, but I think this scenario doesn't require multi-targeting since .NET 5 seems to be backwards compatible with asp.net core 3.1

**Comment by nza-dk** [comment]
I would have thought that it would pollute my publish folder with old .NET framework, but I just tested with a new portable .NET 5 project, and it seems clean and able to run on a server with only .NET 5 installed.
It sure is getting easier and easier working with .NET 🙂
