### ISSUE TITLE
LICENSE ?

### ISSUE THREAD

**Issue by keyone2693** [imazen/imageflow-dotnet-server#40]
hi 

thanks for this awesome package

as an Iranian, we can not pay for any foreign product
so as you guessed it we can not pay for this one too

but the licensing is a bit confusing to me
just read the licencing still didn't find a solution to use it for free!
is there any plan that we could use for our website?

**Comment by lilith** [comment]
Well, if your project is open source you can use it for free.

**Comment by keyone2693** [comment]
You mean we still get that RedDotWatermark?

**Comment by lilith** [comment]
Nope, just set your project URL per the readme
