### ISSUE TITLE
Trouble with remote image handling

### ISSUE THREAD

**Issue by atkulp** [imazen/imageflow-dotnet-server#41]
I've been trying to port over some old ImageResizer code to modern ASP.NET Core Imageflow.  I'm not seeing enough information on how to use the remote image feature though.  I did what seemed correct, but can't ever get it to validate the signature.

I initialize remote support as the following:
```
services.AddImageflowRemoteReaderService(new RemoteReaderServiceOptions
{
        SigningKey = "abc123etcetcetc"
}
.AddPrefix("/remote"));

```
Seems pretty basic.  Now, in my main code, I have a remote URL and the prefix and host for imageflow.  It looks like this:
Config.RemoteHost = "https://my-imageflow.com/remote"
ImageUrl = "http://i.ytimg.com/vi/lJlEQim-yMo/0.jpg"
ImageUrlWithoutScheme = "i.ytimg.com/vi/lJlEQim-yMo/0.jpg"

To craft my URL to embed in the page, I calculate it thus (from Imazen.Common.Helpers):
`Signatures.SignRequest($"{Config.RemoteHost}/{ImageUrlWithoutScheme}", "abc123etcetcetc")`

This yields:
`https://my-imageflow.com/remote/i.ytimg.com/vi/lJlEQim-yMo/0.jpg?signature=0_BuoKWDPoSl5QK-wZh_GQ`
as expected.  When I attempt to resolve it though, I get:
```
You are not authorized to access the given resource.
Invalid request signature
```
What am I missing?  Exactly what am I supposed to pass to the SignRequest function (include "remote", imageflow server url, etc)?  Does it matter about where slashes are on the `AddPrefix` line?

I tried to just make it easy on myself and disable signing completely:
`app.UseImageFlow(...).SetRequestSignatureOptions(new RequestSignatureOptions(SignatureRequired.Never, new string[] { }))`
but that didn't seem to make a difference (what does DefaultSigningKeys mean here anyway?).

Any help would be much appreciated!

**Comment by lilith** [comment]
You're not using `Imageflow.Server.Storage.RemoteReader.RemoteReaderService.EncodeAndSignUrl(string url, string key)`

You're using the general request signing feature instead. I can work up an example.

**Comment by lilith** [comment]
See https://github.com/imazen/imageflow-dotnet-server/blob/main/src/Imageflow.Server.Storage.RemoteReader/README.md

## Usage

```c#
// The origin file
var remoteUrl = "https://imageflow-resources.s3-us-west-2.amazonaws.com/test_inputs/imazen_400.png";
// We encode it, but this doesn't add the /remote/ prefix since that is configurable
var encodedRemoteUrl = RemoteReaderService.EncodeAndSignUrl(remoteUrl, remoteReaderKey);
// Now we add the /remote/ prefix and add some commands
var modifiedUrl = $"/remote/{encodedRemoteUrl}?width=100";
```

If we are also doing request signing (a different signing key and purpose), we would use,
```c#
var signedModifiedUrl = Imazen.Common.Helpers.Signatures.SignRequest(modifiedUrl, requestSigningKey);

//This of course assumes that in Startup.cs you set requestSigningKey as one of the valid keys
app.UseImageflow(new ImageflowMiddlewareOptions()
                    .SetRequestSignatureOptions(
                        new RequestSignatureOptions(SignatureRequired.ForAllRequests, 
                                new []{requestSigningKey})
                    ));
                                
```

**Comment by atkulp** [comment]
That did it.  Thanks so much for such a quick response!

**Comment by lilith** [comment]
No problem! Let me know if you need anything else.
