### ISSUE TITLE
Question: Is it possible to run remote reader without signing?

### ISSUE THREAD

**Issue by atkulp** [imazen/imageflow-dotnet-server#42]
In Image Resizer, you could either sign requests or embed the URL directly without the scheme.  Is it possible to do something similar with imageflow?  Preferably with a hook to check for domain or some other validation before serving...

**Comment by lilith** [comment]
For security and url encoding reasons all remote requests must be
encrypted. Do you have a use case where that isn't feasible?

**Comment by atkulp** [comment]
Just to match features with Image Resizer. It would make it easier as we upgrade our site to keep the behavior the same as we update each section.  It seems good to allow for maximum configurability anyway.

**Comment by lilith** [comment]
I feel that the original feature was a mistake. It didn't allow for
querystrings in the remote url nor certain characters, and essentially
permitted proxying by any client. If you feel it is worth the security risk
it would be easy to fork your own plugin.

**Comment by atkulp** [comment]
Ok. Thanks for responding.  I agree the original limitations for the feature were a problem.  I decided to condition my code during my transition so it uses the old way or new based on a feature flag.
