### ISSUE TITLE
add cors headers to file response

### ISSUE THREAD

**Issue by keyone2693** [imazen/imageflow-dotnet-server#46]
tnx for the awesome package

I have something like this 

`             
 app.UseStaticFiles(new StaticFileOptions
            {
                FileProvider = new PhysicalFileProvider(
                Path.Combine(env.ContentRootPath, "files")),
                RequestPath = "/files",
                OnPrepareResponse = ctx =>
                {
                    ctx.Context.Response.Headers.Append("Access-Control-Allow-Origin", "*");
                    ctx.Context.Response.Headers.Append("Access-Control-Allow-Headers",
                      "Origin, X-Requested-With, Content-Type, Accept");
                }
 });
`

and it's working just fine 
it's for when I want to fetch an image from my client with js

but when I am using image flow its stop working 
and when I looked at the network tab
I can see that those headers were not added

and I have this error

_Access to fetch at 'https://....8.png?width=150' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

how can I solve this?

**Comment by lilith** [comment]
Would you be willing to share your solution in case others run across this
issue?

**Comment by keyone2693** [comment]
Actually, 
Just change my client to work without fetching images

I think the asp core own cors policy is enough 
And maybe  we don't need to add cors policy headers to the static file itself

But for sure when we using image flow
Those headers that added with UseStaticFiles just disappear

**Comment by lilith** [comment]
The middleware isn't involved with the static file middleware - nothing
from there would be intended to affect images.

**Comment by keyone2693** [comment]
I was talking about affecting static files response headers
