### ISSUE TITLE
What is the equivalent of the human friendly configuration from ImageResizer for RemoteReader?

### ISSUE THREAD

**Issue by twwilliams** [imazen/imageflow-dotnet-server#52]
With ImageResizer, we were able to use URL rewriting to make the use of remote URLs transparent.

In our CSHTML views, we would author something like:

```
/special-images/image.jpg?cache=yes&width=500
```

We then had a URL rewriting rule looked like:

```xml
<rule name="resizer remote images">
    <match url="special-images/(.+)" />
    <action type="Rewrite" url="remote/server.example.com/images/{R:1}" />
</rule>
```

And the code served to the browser would have a URL like:

```
/special-images/08f1a2712aa4455ab7e7a44cb7b9640a.jpg?cache=yes&width=500
```

And we have the domain whitelisted in Application_Start.

I think this is the human-friendly syntax as described at https://imageresizing.net/docs/v4/plugins/remotereader

How do we do the same thing with ImageFlow.Server?

**Comment by lilith** [comment]
You can either use AddRewiteHandler like in the readme or a general
rewriting module like this:

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-5.0

**Comment by twwilliams** [comment]
I have the rewrite in place, and it does look like ImageFlow.Server.Storage.RemoteReader is trying to retrieve the image, but I'm getting an error about a missing or invalid signature:

Imageflow.Server.Storage.RemoteReader.RemoteReaderService: Warning: Missing or Invalid signature on remote path: /remote/...

I have a signing key configured:

```csharp
var remoteReaderServiceOptions = new RemoteReaderServiceOptions
{
	SigningKey = "00e17d53-86b7-487d-ba15-7a9eb759e5bf"
}
.AddPrefix("/remote/");

services.AddImageflowRemoteReaderService(remoteReaderServiceOptions);
```

Do I need to whitelist the server domain somehow?

**Comment by twwilliams** [comment]
And even if I avoid the rewrites and explicitly create the URL, I get the same error

```razor
@{
    var remoteUrl = "http://server.example.com/images/08f1a2712bb4458ab7e7a44cb7e6f640a.jpg";
    var encodedRemoteUrl = RemoteReaderService.EncodeAndSignUrl(remoteUrl, "00e17d53-86b7-487d-ba15-7a9eb759e5bf");
    var modifiedUrl = $"/remote/{encodedRemoteUrl}";
}
<img src="@modifiedUrl">
```

Going through the source code, it looks like the hmac in the encoded value doesn't match what is expected.

**Comment by twwilliams** [comment]
The signature problem was due to an IIS-level rewrite that was converting all URLs to lowercase.

I ended up implementing the rewriting I needed by creating an IRule class and adding it into the rewrite middleware we already had in place in Startup.cs.
