### ISSUE TITLE
Out of sequence sharpen commands fail to apply sharpen filter

### ISSUE THREAD

**Issue by JAMAS** [imazen/imageflow-dotnet-server#56]
### Works
?f.sharpenwhen=always&down.filter=cubic_sharp&up.filter=cubic_sharp&f.sharpen=33
### Doesn’t work
 ?f.sharpen=33&f.sharpenwhen=always&down.filter=cubic_sharp&up.filter=cubic_sharp

**Comment by lilith** [comment]
These look identical to me, even if I go up to 50% sharpening.  Can you share the versions of Imageflow and Imageflow.NET Server you are using? I'm testing with `libimageflow release 1.5.8-rc62 (1f6dc67ee* 2021-03-29) for x86_64-pc-windows-msvc`

**Comment by lilith** [comment]
Unable to reproduce issue, reopen if issue re-occurs
