### ISSUE TITLE
Will v0.6.2 be published to nuget.org?

### ISSUE THREAD

**Issue by edmacdonald** [imazen/imageflow-dotnet-server#57]
Hi Lilith,

I see the `v0.6.2` release on the main page from January, but it doesn't yet appear in nuget.org.  Is it still your intent to publish to nuget.org?

Thanks,
-Ed

**Comment by lilith** [comment]
It is, I just hit a wall/bug on the CI deployment. I'm going to try again
this week. I'm really sorry for the delay on this.

**Comment by edmacdonald** [comment]
No worries, I know how frustrating it can be dealing with build issues.  If there is anything I can do to help, please ping me.

**Comment by lilith** [comment]
Finally! It's uploaded. Turns out there was a secondary account attached to the nuget account which needed 2fa and had been locked out, I think that was causing all API keys to fail.
