### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by hn1** [imazen/imageflow-dotnet-server#69]
Hi
Is there any chance you could give us an approximate release date?
Thanks

**Comment by lilith** [comment]
There have been 51 releases: https://github.com/imazen/imageflow-dotnet-server/releases

This is production-ready. The version number indicates API compatibility - semver style.

**Comment by hn1** [comment]
Great. Thank you.

**Comment by hn1** [comment]
Hi,
We need some assistamce in installing and configuring ImageFlow in a .NET Core application.
1- How do we buy a licence. 
2- Is there any technical support (an hours worth) just to help us get started?
Thanks

**Comment by lilith** [comment]
1. Imageflow and ImageResizer are bundled together. Pricing is sliding scale depending on your organization size: https://imageresizing.net/pricing
2.  We offer an e-mail support plan for $300/mo. You can change your subscription on the customer portal at any time.

**Comment by hn1** [comment]
Thanks.
