### ISSUE TITLE
support other CDN?

### ISSUE THREAD

**Issue by GerwinFleurop** [imazen/imageflow-dotnet-server#8]
Hey,

I was wondering which CDN's you support
Is there anything other than Azure BlobStorage & ImageFlowService.

Perhaps Cloudinary or Cloudflare?
I know that there's a list on your website:
Amazon CloudFront
Azure CDN
CDNConnect
Turbobytes
Akami
MaxCDN
NetDNA
BitGravity
Level3
Limelight
Voxel

are all of these supported aswell?

Kind regards

**Comment by lilith** [comment]
Any CDN that allows for a custom origin server is compatible with Imageflow.Server.

**Comment by GerwinFleurop** [comment]
Oo - I like the sound of that,
So I downloaded the example project, in it there's an Imageflow.Server.Storage.S3 project with the title
<Title>Imageflow.Server.Storage.S3 - Service for fetching source images from S3.</Title>
Is caching the images that are created to a CDN also possible with a 'default' implementation?

**Comment by lilith** [comment]
The S3 and Azure plugins are for fetching unmodified files from blob storage befofe they are processed. The processed files would be cached by the CDN which acts as a reverse proxy. No need to explicitly 'cache' to the CDN at all.

**Comment by GerwinFleurop** [comment]
That's exactly what we're after,
Just to make sure I'm understanding this correctly.
We just have to setup a server, put ImageFlow on there, and setup the CustomOriginServer in the customization steps of our CDN?

Thank you for your help thus far.

**Comment by lilith** [comment]
That's correct. 
![Resizer-Cloud-Revised](https://user-images.githubusercontent.com/107935/86491403-0b0d8b80-bd28-11ea-9005-7ebd8d9116b5.png)

**Comment by GerwinFleurop** [comment]
Perfect! Thank you for all your help!

Kind regards,
Gerwin
