### ISSUE TITLE
Add support for signed or encrypted URLs

### ISSUE THREAD

**Issue by lilith** [imazen/imageflow-dotnet-server#9]

**Comment by edmacdonald** [comment]
How about this..
https://github.com/imazen/imageflow-dotnet-server/pull/11

:)

**Comment by lilith** [comment]
That's great! I also want to support full URL encryption/signing, such that DDOS attacks can be completely prevented by only allowing encrypted/signed URLs.

**Comment by edmacdonald** [comment]
Have you any thoughts on how you want to do this?  Depending on the approach, it might also be used to expose a way to modify outbound requests.  These are some things I would find very helpful in the RemoteReader.  I was about to take a crack at them, but wanted to get your thoughts first...
- add a custom UserAgent string
- add an auth header based on destination domain
- clean known, unnecessary params (eg other resizers)

Perhaps a pipeline analogous to the ASPNetCore pipeline where plugins or in-line lambdas could operate on the inbound and outbound requests.

**Comment by lilith** [comment]
I wasn't planning on re-implementing RemoteReader with this, so I'd encourage you to implement this there. I think lambdas could be a good idea, but I would say think about if you want to be tied to a particular http client class when you design it. It also might be worth adding some unit and integration tests to ensure it can be tested.
